const http = require('http');

const server = http.createServer( (req,res)=>{

    console.log= ("Lon generated by index file from node app")
    res.write("Welcome to NODE App - Modify");
    res.end();
});

server.listen(3000);

/*

npm init or npm init --yes

OS(Linux)
NodeJS (Software / CLI)
Port (3000)



Command Terminal 
-----------------
node index.js
*/



